# Generated by Django 6.0 on 2026-01-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_correction_ref_message_is_correction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='learn_language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='speak_language',
        ),
        migrations.RemoveField(
            model_name='voiceroom',
            name='language',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='voiceroom',
            name='category',
            field=models.CharField(default='Chill', max_length=50),
        ),
    ]
