# Generated by Django 6.0 on 2026-01-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_voice_bio_profileimage_userinteraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_in',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Everyone', 'Everyone')], default='Everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_age_pref',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_age_pref',
            field=models.IntegerField(default=18),
        ),
    ]
