# Generated by Django 6.0 on 2026-01-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_interested_in_profile_max_age_pref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='India 🇮🇳', max_length=50),
        ),
    ]
