# Generated by Django 6.0 on 2026-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_google_id_profile_google_pic_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
