# Generated by Django 6.0 on 2026-01-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
