# Generated by Django 5.0.1 on 2026-01-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message_image_alter_block_id_alter_chatroom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='can_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='can_send_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='can_video',
            field=models.BooleanField(default=False),
        ),
    ]
