# Generated by Django 5.0.1 on 2026-01-21 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chatroom_can_call_chatroom_can_send_media_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_content/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='content_thumbs/')),
                ('caption', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('story', 'Story (24h)'), ('reel', 'Reel (Video)'), ('post', 'Post (Image)')], default='post', max_length=10)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
